In [ ]:
import pandas as pd 
import numpy as np
import re 
import nltk 
nltk.download('stopwords') 
from nltk.corpus import stopwords 
from nltk.stem.porter import PorterStemmer 
corpus = []  

data= pd.read_csv('newdata.csv')

print(data.head())

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer

#Define a TF-IDF Vectorizer Object. Remove all english stopwords
tfidf = TfidfVectorizer(stop_words='english')

#Replace NaN with an empty string
data['text'] = data['text'].fillna('')

data=data.head(200000)

#Construct the required TF-IDF matrix by applying the fit_transform method on the overview feature
tfidf_matrix = tfidf.fit_transform(data['text'])

#Output the shape of tfidf_matrix
tfidf_matrix.shape



(10000, 18165)

In [29]:
from sklearn.metrics.pairwise import linear_kernel

# Compute the cosine similarity matrix
cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)

In [30]:
print(cosine_sim)

[[1.         0.12034298 0.1519807  ... 0.02451437 0.04606466 0.02050774]
 [0.12034298 1.         0.0304503  ... 0.         0.01231531 0.        ]
 [0.1519807  0.0304503  1.         ... 0.01407092 0.02186942 0.00726177]
 ...
 [0.02451437 0.         0.01407092 ... 1.         0.08612066 0.04293131]
 [0.04606466 0.01231531 0.02186942 ... 0.08612066 1.         0.01838767]
 [0.02050774 0.         0.00726177 ... 0.04293131 0.01838767 1.        ]]
